# Week 8 - MINST Bagging

In [ ]:
from keras.datasets import mnist
from keras.utils import np_utils
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score

In [2]:
%pylab inline

In [3]:
def load_data():
    print 'Loading data...'
    (X_train, y_train), (X_test, y_test) = mnist.load_data()

    X_train = X_train.astype('float32')
    X_test = X_test.astype('float32')

    X_train /= 255
    X_test /= 255

    y_train = np_utils.to_categorical(y_train, 10)
    y_test = np_utils.to_categorical(y_test, 10)

    X_train = np.reshape(X_train, (60000, 784))
    X_test = np.reshape(X_test, (10000, 784))

    print 'Data loaded.'
    return [X_train, X_test, y_train, y_test]

In [4]:
def run_model(data=None, model=None, epochs=20, batch=256):
    try:
        start_time = time.time()
        if data is None:
            X_train, X_test, y_train, y_test = load_data()
        else:
            X_train, X_test, y_train, y_test = data

IndentationError: unexpected unindent (<ipython-input-4-8bd35b006114>, line 7)

In [5]:
X_train, X_test, y_train, y_test = load_data()

Loading data...
Data loaded.


Need to convert array encoding to the actual digit to make kmeans work easier. 

In [25]:
y_test_conv = []

for i in range(1, len(y_test)):
    y_test_conv += np.where(y_test[i] == 1)

In [26]:
y_train_conv = []

for i in range(1, len(y_train)):
    y_train_conv += np.where(y_train[i] == 1)

In [27]:
y_train_conv

[array([0]),
 array([4]),
 array([1]),
 array([9]),
 array([2]),
 array([1]),
 array([3]),
 array([1]),
 array([4]),
 array([3]),
 array([5]),
 array([3]),
 array([6]),
 array([1]),
 array([7]),
 array([2]),
 array([8]),
 array([6]),
 array([9]),
 array([4]),
 array([0]),
 array([9]),
 array([1]),
 array([1]),
 array([2]),
 array([4]),
 array([3]),
 array([2]),
 array([7]),
 array([3]),
 array([8]),
 array([6]),
 array([9]),
 array([0]),
 array([5]),
 array([6]),
 array([0]),
 array([7]),
 array([6]),
 array([1]),
 array([8]),
 array([7]),
 array([9]),
 array([3]),
 array([9]),
 array([8]),
 array([5]),
 array([9]),
 array([3]),
 array([3]),
 array([0]),
 array([7]),
 array([4]),
 array([9]),
 array([8]),
 array([0]),
 array([9]),
 array([4]),
 array([1]),
 array([4]),
 array([4]),
 array([6]),
 array([0]),
 array([4]),
 array([5]),
 array([6]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([7]),
 array([1]),
 array([6]),
 array([3]),
 array([0]),
 array([2]),
 array([1]),

In [ ]:
kmeans = KMeans(n_clusters=10, random_state=0).fit(X_train, y = y_test_conv)

In [ ]:
y_pred = kmeans.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
print(y_pred)

In [ ]:
print(y_test)

In [ ]:
y_test[4]